### ISSUE TITLE
0.07: test failures with older gcc (?)

### ISSUE THREAD

**Issue by eserte** [karupanerura/Geo-Hex-V3-XS#2]
The CPAN Testers Matrix shows a lot of failures: http://matrix.cpantesters.org/?dist=Geo-Hex-V3-XS%200.07

One reason could be the used gcc compiler: according to
http://analysis.cpantesters.org/solved?distv=Geo-Hex-V3-XS-0.07#conf%3Agccversion
it seems to fail for gcc 4.5 and older (disregard the clang versions in this list).

**Comment by karupanerura** [comment]
Thank you for reporting!
This bug is fixed in 0.11 maybe.

**Comment by karupanerura** [comment]
So if this bug is happened again, re-open the issue.
